CREATE TABLESPACE xe_data
DATAFILE '/u01/app/oracle/oradata/XE/xe_data.dbf'
SIZE 1G;

CREATE USER XE IDENTIFIED BY oracle
DEFAULT TABLESPACE xe_data
TEMPORARY TABLESPACE temp;

GRANT UNLIMITED TABLESPACE TO xe;
GRANT CREATE SESSION TO xe;
GRANT CREATE TABLE TO xe;

GRANT CONNECT, RESOURCE TO xe;