version: "3"

services:
  oracle:
    image: gvenzl/oracle-xe:11.2.0.2
    environment:
      APP_USER: xe_db
      APP_USER_PASSWORD: oracle
      ORACLE_PASSWORD: oracle
    container_name: oracle
    volumes:
      - data-oracle:/u01/app/oracle/oradata/
    ports:
      - "1521:1521"
    networks:
      - custom_network

networks:
  custom_network:
    external: true

volumes:
  data-oracle: